### ISSUE TITLE
Functorize the underlying buffer type

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-channel#2]
Would be good to be able to select between io-page/cstruct (for the tcpip stack) and strings (for the http stack)

**Comment by samoht** [comment]
See https://github.com/mirage/mirage-http/issues/19

**Comment by djs55** [comment]
(I intended to comment on this issue but I've obviously failed to press the button)

I assume it's the output buffering you would like to functorize over, as the input buffer is tied to the `FLOW.buffer` type. I'll investigate.

**Comment by djs55** [comment]
Hm, I'm not sure how to improve this. The final call to `FLOW.write` needs to have a `Cstruct.t` so we either have to queue up strings and copy in `flush` or copy then in `write_string`.

**Comment by hannesm** [comment]
i suspect now that #29 got merged, this won't be easier. the above linked mirage-http issue returns 404 to me. if you feel this is still relevant, please reopen the issue and provide some more details where which buffer type is to-be-used. thanks!
